### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by rgarrigue** [inventaire/inventaire-deploy#2]
Hi

I'm currently working on a docker setup for inventaire. You can find my work in progress in https://github.com/rgarrigue/docker-inventaire. 

Currenlty I'm having some difficulties related to NodeJS && npm, I thought you could help with for everyone's benefit.

First is the docker build, defined by https://github.com/rgarrigue/docker-inventaire/blob/master/Dockerfile. The log : [docker.build.txt](https://github.com/inventaire/inventaire-deploy/files/1095391/docker.build.txt). Its end up successfully, but there are errors: lines 7775, 7830, 7853, 7912, 8635, 8658, 8695, 8718, 8731. And maybe other. 
Some are obvious, 8718 is missing bower. I can fix that, but maybe that's you package.json missing this. Maybe, I don't know much about NodeJS packaging and what should be done where.

Second optional concern is size : 947 MB. This is a bit much, how can that be reduced ? I'm pretty sure I should clean after compiling, or minify resulting app, or compile it outside of the container + copy the compiled result + installing only running dependencies

Third thing is docker-compose. Good practise with docker is, app in a container, elasticsearch in another, couchdb in a third one. And nginx & prerender in the 4th and the 5th, but later. Here's the result with my flawed (as stated in the first point) inventaire container

```
➜  docker-inventaire git:(master) ✗ docker-compose up
Starting inventaire_couchdb ... 
Starting inventaire_couchdb
Starting inventaire_elasticsearch ... 
Starting inventaire_elasticsearch ... done
Starting inventaire_application ... 
Starting inventaire_application ... done
Attaching to inventaire_couchdb, inventaire_elasticsearch, inventaire_application
inventaire_couchdb | Apache CouchDB 1.6.1 (LogLevel=info) is starting.
inventaire_couchdb | Apache CouchDB has started. Time to relax.
inventaire_couchdb | [info] [<0.32.0>] Apache CouchDB has started on http://0.0.0.0:5984/
inventaire_application | npm info it worked if it ends with ok
inventaire_application | npm info using npm@3.10.10
inventaire_application | npm info using node@v6.11.0
inventaire_application | npm info lifecycle inventaire@2.1.0~prestart: inventaire@2.1.0
inventaire_application | npm info lifecycle inventaire@2.1.0~start: inventaire@2.1.0
inventaire_application | 
inventaire_application | > inventaire@2.1.0 start /opt/inventaire
inventaire_application | > coffee server.coffee
inventaire_application | 
inventaire_elasticsearch | [2017-06-22T15:31:13,328][INFO ][o.e.n.Node               ] [] initializing ...
inventaire_application | TypeError: Cannot read property 'require' of undefined
inventaire_application |     at Object.<anonymous> (/opt/inventaire/server.coffee:16:7)
inventaire_application |     at Object.<anonymous> (/opt/inventaire/server.coffee:1:1)
inventaire_application |     at Module._compile (module.js:570:32)
inventaire_application |     at Object.exports.run (/opt/inventaire/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
inventaire_application |     at compileScript (/opt/inventaire/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
inventaire_application |     at compilePath (/opt/inventaire/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
inventaire_application |     at Object.exports.run (/opt/inventaire/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
inventaire_application |     at Object.<anonymous> (/opt/inventaire/node_modules/coffee-script/bin/coffee:15:45)
inventaire_application |     at Module._compile (module.js:570:32)
inventaire_application |     at Object.Module._extensions..js (module.js:579:10)
inventaire_application |     at Module.load (module.js:487:32)
inventaire_application |     at tryModuleLoad (module.js:446:12)
inventaire_application |     at Function.Module._load (module.js:438:3)
inventaire_application |     at Module.runMain (module.js:604:10)
inventaire_application |     at run (bootstrap_node.js:389:7)
inventaire_application |     at startup (bootstrap_node.js:149:9)
inventaire_application |     at bootstrap_node.js:504:3
inventaire_application | 
inventaire_application | 
inventaire_application | npm info lifecycle inventaire@2.1.0~start: Failed to exec start script
inventaire_application | npm ERR! Linux 4.8.0-52-generic
inventaire_application | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
inventaire_application | npm ERR! node v6.11.0
inventaire_application | npm ERR! npm  v3.10.10
inventaire_application | npm ERR! code ELIFECYCLE
inventaire_application | npm ERR! inventaire@2.1.0 start: `coffee server.coffee`
inventaire_application | npm ERR! Exit status 1
inventaire_application | npm ERR! 
inventaire_application | npm ERR! Failed at the inventaire@2.1.0 start script 'coffee server.coffee'.
inventaire_application | npm ERR! Make sure you have the latest version of node.js and npm installed.
inventaire_application | npm ERR! If you do, this is most likely a problem with the inventaire package,
inventaire_application | npm ERR! not with npm itself.
inventaire_application | npm ERR! Tell the author that this fails on your system:
inventaire_application | npm ERR!     coffee server.coffee
inventaire_application | npm ERR! You can get information on how to open an issue for this project with:
inventaire_application | npm ERR!     npm bugs inventaire
inventaire_application | npm ERR! Or if that isn't available, you can get their info via:
inventaire_application | npm ERR!     npm owner ls inventaire
inventaire_elasticsearch | [2017-06-22T15:31:13,832][INFO ][o.e.e.NodeEnvironment    ] [lGsjDOe] using [1] data paths, mounts [[/ (none)]], net usable_space [666gb], net total_space [928.8gb], spins? [possibly], types [aufs]
inventaire_application | npm ERR! There is likely additional logging output above.
inventaire_elasticsearch | [2017-06-22T15:31:13,834][INFO ][o.e.e.NodeEnvironment    ] [lGsjDOe] heap size [1.9gb], compressed ordinary object pointers [true]
inventaire_application | 
inventaire_application | npm ERR! Please include the following file with any support request:
inventaire_application | npm ERR!     /opt/inventaire/npm-debug.log
inventaire_elasticsearch | [2017-06-22T15:31:13,910][INFO ][o.e.n.Node               ] node name [lGsjDOe] derived from node ID [lGsjDOeaTLSHuMr262N6IQ]; set [node.name] to override
inventaire_elasticsearch | [2017-06-22T15:31:13,912][INFO ][o.e.n.Node               ] version[5.4.2], pid[1], build[929b078/2017-06-15T02:29:28.122Z], OS[Linux/4.8.0-52-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b12]
inventaire_elasticsearch | [2017-06-22T15:31:13,912][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch]
inventaire_application exited with code 1
inventaire_elasticsearch | [2017-06-22T15:31:20,813][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [aggs-matrix-stats]
inventaire_elasticsearch | [2017-06-22T15:31:20,814][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [ingest-common]
inventaire_elasticsearch | [2017-06-22T15:31:20,816][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [lang-expression]
inventaire_elasticsearch | [2017-06-22T15:31:20,820][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [lang-groovy]
inventaire_elasticsearch | [2017-06-22T15:31:20,823][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [lang-mustache]
inventaire_elasticsearch | [2017-06-22T15:31:20,824][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [lang-painless]
inventaire_elasticsearch | [2017-06-22T15:31:20,825][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [percolator]
inventaire_elasticsearch | [2017-06-22T15:31:20,827][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [reindex]
inventaire_elasticsearch | [2017-06-22T15:31:20,829][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [transport-netty3]
inventaire_elasticsearch | [2017-06-22T15:31:20,830][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded module [transport-netty4]
inventaire_elasticsearch | [2017-06-22T15:31:20,835][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded plugin [ingest-geoip]
inventaire_elasticsearch | [2017-06-22T15:31:20,839][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded plugin [ingest-user-agent]
inventaire_elasticsearch | [2017-06-22T15:31:20,840][INFO ][o.e.p.PluginsService     ] [lGsjDOe] loaded plugin [x-pack]
inventaire_elasticsearch | [2017-06-22T15:31:28,493][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/48] [Main.cc@128] controller (64 bit): Version 5.4.2 (Build 0986144d2d42c8) Copyright (c) 2017 Elasticsearch BV
inventaire_elasticsearch | [2017-06-22T15:31:28,606][INFO ][o.e.d.DiscoveryModule    ] [lGsjDOe] using discovery type [zen]
inventaire_elasticsearch | [2017-06-22T15:31:32,659][INFO ][o.e.n.Node               ] initialized
inventaire_elasticsearch | [2017-06-22T15:31:32,660][INFO ][o.e.n.Node               ] [lGsjDOe] starting ...
inventaire_elasticsearch | [2017-06-22T15:31:33,631][INFO ][o.e.t.TransportService   ] [lGsjDOe] publish_address {172.19.0.3:9300}, bound_addresses {[::]:9300}
inventaire_elasticsearch | [2017-06-22T15:31:33,680][INFO ][o.e.b.BootstrapChecks    ] [lGsjDOe] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
inventaire_elasticsearch | [2017-06-22T15:31:37,006][INFO ][o.e.c.s.ClusterService   ] [lGsjDOe] new_master {lGsjDOe}{lGsjDOeaTLSHuMr262N6IQ}{HgQftXkeSnypeL30ENo62g}{172.19.0.3}{172.19.0.3:9300}{ml.enabled=true}, reason: zen-disco-elected-as-master ([0] nodes joined)
inventaire_elasticsearch | [2017-06-22T15:31:37,143][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [lGsjDOe] publish_address {172.19.0.3:9200}, bound_addresses {[::]:9200}
inventaire_elasticsearch | [2017-06-22T15:31:37,161][INFO ][o.e.n.Node               ] [lGsjDOe] started
inventaire_elasticsearch | [2017-06-22T15:31:38,755][INFO ][o.e.l.LicenseService     ] [lGsjDOe] license [350b3254-a1ad-4462-92cd-c76a414ea853] mode [trial] - valid
inventaire_elasticsearch | [2017-06-22T15:31:38,828][INFO ][o.e.g.GatewayService     ] [lGsjDOe] recovered [3] indices into cluster_state
inventaire_elasticsearch | [2017-06-22T15:31:40,327][INFO ][o.e.c.r.a.AllocationService] [lGsjDOe] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.watches][0], [.monitoring-es-2-2017.06.22][0]] ...]).
inventaire_elasticsearch | [2017-06-22T15:32:42,215][INFO ][o.e.c.m.MetaDataCreateIndexService] [lGsjDOe] [.triggered_watches] creating index, cause [auto(bulk api)], templates [triggered_watches], shards [1]/[1], mappings [triggered_watch]
inventaire_elasticsearch | [2017-06-22T15:32:43,413][INFO ][o.e.c.m.MetaDataCreateIndexService] [lGsjDOe] [.monitoring-alerts-2] creating index, cause [auto(bulk api)], templates [.monitoring-alerts-2], shards [1]/[1], mappings [doc]
inventaire_elasticsearch | [2017-06-22T15:32:43,759][INFO ][o.e.c.m.MetaDataCreateIndexService] [lGsjDOe] [.watcher-history-3-2017.06.22] creating index, cause [auto(bulk api)], templates [watch_history_3], shards [1]/[1], mappings [watch_record]
inventaire_elasticsearch | [2017-06-22T15:32:44,387][INFO ][o.e.c.m.MetaDataMappingService] [lGsjDOe] [.watcher-history-3-2017.06.22/Z9H_bHwXTaK_7Yzd3cJIjg] update_mapping [watch_record]
inventaire_elasticsearch | [2017-06-22T15:32:44,791][INFO ][o.e.c.m.MetaDataMappingService] [lGsjDOe] [.watcher-history-3-2017.06.22/Z9H_bHwXTaK_7Yzd3cJIjg] update_mapping [watch_record]
```

Is this server.coffee error related to the flawed ? It doesn't make a lot of sense to me

```
__ = CONFIG.universalPath
_ = __.require 'builders', 'utils'           <=========== line 16
americano = require 'americano'
fs = require 'fs'
```

That's it for now. Later on I'ld like to discuss stuff like default parameters but first, getting it to work !

Best regards,

**Comment by maxlath** [comment]
things I can think of for those different errors:

* ~line 7775~: `client/app/lib/handlebars_helpers/linkify` being missing happens if `https://github.com/inventaire/inventaire#i18n` is cloned before `https://github.com/inventaire/inventaire-client#master`, which should have been fixed by https://github.com/inventaire/inventaire/commit/7a02a9c49c6b0b53b35353481b055f7f125fc622 . As stated in the commit message `[i18n scripts have] an horrible dependency graph that should be fixed at some point`, that is, repos depending on other repos scripts, sometimes bidirectionally (the server using scripts from the client repo and vis-versa) all my apologies for that.
* ~lines 7830,8731~: patches are an old hacky way to make tiny corrections to dependencies without having to fork it (in the [present case](https://github.com/inventaire/inventaire/blob/e750087e99fdc0dcac551c4a097e9120db0c21cd/scripts/patches/americano_err_stacktrace), trying to make `americano` log error stack). I presume the path resolution system is bad/tightlly coupled to my own setup: it here assumed that you installed the server in the `/opt/inventaire` under the name `inventaire` so that `node_modules` can be found at `/opt/inventaire/inventaire/node_modules`. Fix: rewrite path system or simply remove patches. [Update: fixed by https://github.com/inventaire/inventaire/commit/403889ef3085eabbd271de867b9fe35a1e7cac30 and https://github.com/inventaire/inventaire-client/commit/15249381c47615fe591f8e040e04d836b0fba763 ]
* lines 7853, 7881, 7912 : fixed by https://github.com/inventaire/inventaire/commit/03fbb6dde18df13357a6f3daea80e4d72dbecd48 but the `err.body` being undefined means that an other error is to be expected
* ~line 8635~: weird, `ls` should have been installed at that point. Anyway, the whole [`slim_package` script is obsolete and was thus removed](https://github.com/inventaire/inventaire-client/commit/12a0565df846a5f8e5d279dc5aaca10e9ba90e0d)
* ~lines 8658,8688~: missing directories, should have been fixed by https://github.com/inventaire/inventaire-client/commit/c0cd0b5
* lines 8695,8718: this seems to show that `npm install` in the client repo failed to include devDependencies that are required to run the different scripts, presumably because of the `NODE_ENV=production`. Two way to fix it: either run build scripts with `NODE_ENV=dev` or we should move most, if not all, `devDependencies` to normal `dependencies`.

Measures to make those install scripts more reliable:
* too many errors were probably being ignored because they aren't critical, but that's really not helping other people using it: all script should progressively be prefixed with [`set -eu`](http://jvns.ca/blog/2017/03/26/bash-quirks/), so that if any command fails (exit with a non-zero code), the whole script fail, helping those issues to be detected and fixed. First commits in this sense: https://github.com/inventaire/inventaire-client/commit/d2c3e28

I'm afraid the image weight is due to big dependency tree in `node_modules` folders: on my local install, node_modules from the server and client combined weight some 600MB. This hints toward solving the lines 8695,8718 issues by moving scripts dependencies to `dependencies` to be able to install those in production mode, thus avoiding to install test environments and so one. Unfortunately, that seems to be what you have done already (using `NODE_ENV=production`) and you still get that big 1GB folder ><. Could you run something like `du -sh` in the generated image and see what takes so much space?

Nginx and prerender are indeed not hard dependencies: I work in development without either running.

**Comment by maxlath** [comment]
closing now that we have a dedicated Docker repo, [`inventaire/docker-inventaire`](https://github.com/inventaire/docker-inventaire): docker specific issues should go now there
